# LED CONFIG --- CHOOSE
# ---
# include:
#   - board: nice_nano_v2
#     shield: corne_left
#   - board: nice_nano_v2
#     shield: corne_right
#   - board: nice_nano_v2
#     shield: settings_reset
# NICE!VIEW CONFIG --- CHOOSE
---
include:
  - board: nice_nano_v2
    # shield: corne_left nice_view_adapter nice_view
    shield: corne_left
    snippet: studio-rpc-usb-uart # ZMK STUDIO
  - board: nice_nano_v2
    # shield: corne_right nice_view_adapter nice_view
    shield: corne_right
    snippet: studio-rpc-usb-uart # ZMK STUDIO
  - board: nice_nano_v2
    shield: settings_reset
